# 因为 hugo-theme-kiwi主题是基于hugo_extended:0.113.0开发的
image: registry.gitlab.com/pages/hugo/hugo_extended:0.113.0

variables:
  HUGO_ENV: production
  THEME_URL: "github.com/zhenqicai/hugo-theme-kiwi" 

default:
  before_script:
    - apk add --no-cache go curl bash npm
    - hugo mod get -u $THEME_URL
    # To use PostCSS, we must install the following modules. See:
    # - https://gohugo.io/hugo-pipes/postcss/
    # - https://github.com/google/docsy/tree/main#prerequisites
    - npm install postcss postcss-cli autoprefixer

# Use everywhere except on the default branch
test:
  script:
    - hugo --minify
  rules:
    - if: $CI_COMMIT_REF_NAME != $CI_DEFAULT_BRANCH

# Run only on the default branch
pages:
  script:
    - hugo --minify
  artifacts:
    paths:
      - public
  rules:
    - if: $CI_COMMIT_REF_NAME == $CI_DEFAULT_BRANCH

